import { invoke } from '@tauri-apps/api/core';

window.cc3API = {
  minimize: () => invoke('window_minimize'),
  maximize: () => invoke('window_toggle_maximize'),
  close: () => invoke('window_close'),
  getDevices: () => invoke('get_devices'),
  launchScrcpy: (deviceId?: string, customArgs: string[] = []) => invoke('launch_scrcpy', { deviceId, customArgs }),
  adbConnect: (ip: string) => invoke('adb_connect', { ip }),
  adbScreenshot: (deviceId: string) => invoke('adb_screenshot', { deviceId }),
  scanConfigs: () => invoke('scan_configs'),
  launchMcp: (port: number | string, configFileName: string) => invoke('launch_mcp', { port: String(port), configFileName }),
  launchNgrok: (portOrAddress: string, url: string) => invoke('launch_ngrok', { portOrAddress, url }),
  launchKillPort: (port: string) => invoke('launch_kill_port', { port }),
  launchMcpProxy: (port: string) => invoke('launch_mcp_proxy', { port }),
  launchSerena: (port: string) => invoke('launch_serena', { port }),
  mcpApiHealth: (baseUrl: string) => invoke('mcp_api_health', { baseUrl }),
  mcpApiRefreshAll: (baseUrl: string) => invoke('mcp_api_refresh_all', { baseUrl }),
  mcpApiServerStart: (baseUrl: string, serverName: string) => invoke('mcp_api_server_start', { baseUrl, serverName }),
  mcpApiServerStop: (baseUrl: string, serverName: string) => invoke('mcp_api_server_stop', { baseUrl, serverName }),
  mcpApiServerDisable: (baseUrl: string, serverName: string) => invoke('mcp_api_server_disable', { baseUrl, serverName }),
  mcpApiServerRefresh: (baseUrl: string, serverName: string) => invoke('mcp_api_server_refresh', { baseUrl, serverName }),
  mcpApiRestart: (baseUrl: string) => invoke('mcp_api_restart', { baseUrl }),
  gitStatus: (cwd: string) => invoke('git_status', { cwd }),
  gitRemote: (cwd: string) => invoke('git_remote', { cwd }),
  gitConnectRemote: (cwd: string, url: string) => invoke('git_connect_remote', { cwd, url }),
  gitCreateRemote: (cwd: string) => invoke('git_create_remote', { cwd }),
  gitFetch: (cwd: string) => invoke('git_fetch', { cwd }),
  gitStagePush: (cwd: string) => invoke('git_stage_push', { cwd }),
  zipProject: (cwd: string) => invoke('zip_project', { cwd }),
};
